[package]
name = "massa_signature"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = { version = "0.4", features = ["check"] }
displaydoc = "0.2"
ed25519-dalek = { version = "2.0", features = ["batch"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nom = "7.1"
rand = "0.7"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_serialization = { path = "../massa-serialization" }

[dev-dependencies]
serial_test = "0.10"
serde_json = "1.0"
