[package]
name = "massa-node"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
anyhow = "1.0"
enum-map = { version = "2.4", features = ["serde"] }
lazy_static = "1.4"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.23", features = ["full"] }
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_debug",
] }
tracing-subscriber = "0.3"
paw = "1.0"
structopt = { version = "0.3", features = ["paw"] }
dialoguer = "0.10"
# custom modules
massa_api_exports = { path = "../massa-api-exports" }
massa_api = { path = "../massa-api" }
massa_async_pool = { path = "../massa-async-pool" }
massa_bootstrap = { path = "../massa-bootstrap" }
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_consensus_worker = { path = "../massa-consensus-worker" }
massa_executed_ops = { path = "../massa-executed-ops" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_execution_worker = { path = "../massa-execution-worker" }
massa_logging = { path = "../massa-logging" }
massa_final_state = { path = "../massa-final-state" }
massa_ledger_exports = { path = "../massa-ledger-exports" }
massa_ledger_worker = { path = "../massa-ledger-worker" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_network_worker = { path = "../massa-network-worker" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_pool_worker = { path = "../massa-pool-worker" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_protocol_worker = { path = "../massa-protocol-worker" }
massa_pos_worker = { path = "../massa-pos-worker" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time" }
massa_wallet = { path = "../massa-wallet" }
massa_factory_exports = { path = "../massa-factory-exports" }
massa_factory_worker = { path = "../massa-factory-worker" }
massa_grpc = { path = "../massa-grpc" }
# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
beta = []
deadlock_detection = []
sandbox = [
    "massa_bootstrap/sandbox",
    "massa_consensus_worker/sandbox",
    "massa_execution_worker/sandbox",
    "massa_final_state/sandbox",
    "massa_models/sandbox",
    "massa_protocol_exports/sandbox"
]

[build]
rustflags = ["--cfg", "tokio_unstable"]
