[package]
name = "massa_protocol_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.3"
displaydoc = "0.2"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.23", features = ["full"] }
tracing = "0.1"

# custom modules
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_storage = { path = "../massa-storage" }

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
sandbox = ["massa_models/sandbox"]
testing = []